### ISSUE TITLE
"supplier": "NOASSERTION" getting in generated SBOM

### ISSUE THREAD

**Issue by SatishRathore** [microsoft/sbom-tool#280]
using command 

"sbom-tool.exe generate -b  -bc  -pn SBOM.PoC -pv 1.0 -ps PoC -nsb https://www.PoC.com/" 

for every pkg i am getting "supplier": "NOASSERTION"

Am I doing anything wrong ?
{
      "name": "Swashbuckle.AspNetCore.SwaggerUI",
      "SPDXID": "SPDXRef-Package-8D9F0AA9D67828FAEB401376FBF2C5CF2033BCA3ECEA1F5BDC262A7F88A0CC52",
      "downloadLocation": "NOASSERTION",
      "filesAnalyzed": false,
      "licenseConcluded": "NOASSERTION",
      "licenseDeclared": "NOASSERTION",
      "copyrightText": "NOASSERTION",
      "versionInfo": "6.2.3",
      "externalRefs": [
        {
          "referenceCategory": "PACKAGE-MANAGER",
          "referenceType": "purl",
          "referenceLocator": "pkg:nuget/Swashbuckle.AspNetCore.SwaggerUI@6.2.3"
        }
      ],
      "supplier": "NOASSERTION"

**Comment by ryanbrandenburg** [comment]
@sebasgomez238 were you able to figure out what was going on here?

**Comment by Bran89** [comment]
I am having the same issue, I generally have to build project / restore packages at least once before supplier data is retrieved properly.

**Comment by edgarrs** [comment]
@sebasgomez238 , please update with your findings

**Comment by sebasgomez238** [comment]
At the moment supplier information is only retrieved for NPM and NuGet. Here is some information about how it works:

**Nuget:**

- Supplier information is retrieved from either the .nuspec or .nupkg files present in the directory. 

- In the case of dependencies these are detected via the project.assets.json present in every project's '/obj' directory. Example: ( 
  "C:\repos\sbom-tool\src\Microsoft.Sbom.Adapters\obj\project.assets.json").

- The project.assets.json contains the list of dependencies but does not contain supplier information as we don't have access to 
   the individual dependencies' .nuspec/.nupkg files.

- This means that supplier information will not be found for transitive dependencies.

**NPM:**

- Node projects contain a @node_modules directory where every package is listed and its corresponding package.json is 
  present.

- Component Detection parses this package.json and pulls out the supplier information.

- The @node_modules directory is typically created after running `npm install`.

The reason why the project needs to be built in order to capture the information is because the build process usually fetches/restores the projects packages which we then use to retrieve supplier information.

**Comment by THEJRRR** [comment]
Having the build process fetch the project's packages is not ideal, but is working as intended.
