### ISSUE TITLE
Gendocs build hangs

### ISSUE THREAD

**Issue by aasim** [microsoft/sbom-tool#32]
Make any chnages in the IConfiguration.cs file, and that will trigger the gendocs build, however the build currently hangs without showing any error.

Running locally on Ubuntu, the build fails with this error, the package is already present in the feed: 
```
/usr/share/dotnet/sdk/3.1.420/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(241,5): error NETSDK1064: Package Microsoft.CodeAnalysis.VersionCheckAnalyzer, version 3.3.0 was not found. It might have been deleted since NuGet restore. Otherwise, NuGet restore might have only partially completed, which might have been due to maximum path length restrictions. 
```

**Comment by ByAgenT** [comment]
This hangs because of the same reason as #56. .NET 6 migration didn't fix the issue, so future path forward is to work with PowerArgs to push a new version w/ a fix or just remove PowerArgs from the project. Besides that, gendocs pipeline needs complete rehaul and it's probably better to create a script to update docs locally rather than using a pipeline for that, so not enough reasons for me to spend more time on it further.
