### ISSUE TITLE
missing `libMonoPosixHelper` error for 1.6.2 arm builds

### ISSUE THREAD

**Issue by chenrui333** [microsoft/sbom-tool#394]
👋 it looks like 1.6.2 arm builds have missing `libMonoPosixHelper` error.

```
==> /opt/homebrew/Cellar/sbom-tool/1.6.2/bin/sbom-tool generate -b /private/tmp/sbom-tool-test-20230922-7283-1wp2mv -bc /private/tmp/sbom-tool-test-20230922-7283-1wp2mv -pn TestProject -pv 1.2.3 -ps Homebrew -nsb http://formulae.brew.sh/
  Unable to load shared library 'MonoPosixHelper' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libMonoPosixHelper, 0x0001): tried: 'libMonoPosixHelper' (no such file), '/usr/local/lib/libMonoPosixHelper' (no such file), '/usr/lib/libMonoPosixHelper' (no such file), '/private/tmp/sbom-tool-test-20230922-7283-1wp2mv/libMonoPosixHelper' (no such file)
```

relates to https://github.com/Homebrew/homebrew-core/pull/144912

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/6277974050/job/17051360360?pr=144912

**Comment by sebasgomez238** [comment]
@chenrui333 Hello, we are tracking this issue on #223. This issue was recently resolved by moving to the Mono.Unix libraries but this resulted in breaking the tool on Docker so we reverted back to Mono.Posix.NETStandard which does not support arm unfortunately. In the meantime v1.6.1 should work while we resolve this.

**Comment by chenrui333** [comment]
cool, thanks for the pointer. closing this issue now.
