### ISSUE TITLE
Why do .pdb files appear in the output?

### ISSUE THREAD

**Issue by devinfluencer** [microsoft/sbom-tool#627]
Hi,
I scanned a debug build by chance and saw that .pdb files appeared in the output manifest.
Why's this? They are not binaries in the sense of a library.
Regards,
Thomas

**Comment by DaveTryon** [comment]
@devinfluencer, the fundamental point of an SBOM is to provide consumers with a verification that the bits being consumed haven't changed since they were released. That includes verifying that the set of files hasn't changed, so if PDB's exist in the folder being packaged, they need to also exist in the SBOM.

You're correct that PDB files aren't typically binaries in the sense of a library, but a bad actor could potentially disguise a malicious piece of code by changing its extension to `.pdb`. If we were to exclude the file based on the extension, that would create a security hole that we don't want.

If you want to release a debug package without PDB files, it's pretty simple. I'll use Windows shell commands for illustration, but there are counterparts for non-Windows platforms
1. Build normally
2. Use `xcopy /s /e /v` to copy your build output to a new folder
3. Use `del /s /q *.pdb` to scrub the PDB's from the new folder
4. Use the new folder when building your output package and your SBOM

Thanks for your interest in SBOM! I'll go ahead and close this issue out, but please feel free to open a new one if you have other questions.
