### ISSUE TITLE
How about unmanaged C++ code references?

### ISSUE THREAD

**Issue by devinfluencer** [microsoft/sbom-tool#628]
Hi,
do I miss something? I have a mixed C# and C++ solution in VS2022.
I expected to find references to the projects in THIRD-PARTY-LICENSES.txt files in Nuget packages.
![image](https://github.com/user-attachments/assets/b3e1c91c-5fc2-4a79-acab-83619c3cad7e)
Are unmanaged dependencies, be it from Nugets or direct assembly references, listed at all?
Regards,
Thomas

**Comment by DaveTryon** [comment]
Hi, @devinfluencer!

The third-party notice file you're looking at is pulled directly from `skiasharp.nativeassets.win32.2.88.8.nupkg`. The content of that file is determined entirely by the SkiaSharp team, so you might try asking this question at [their issues list](https://github.com/mono/SkiaSharp/issues).

When building the SBOM, we know about the packages (in this case SkiaSharp.NariveAssets.Win32) and about the files on the disk, but we don't know about how those packages were made--for that we'd rely on the SBOM from the respective packages. In this specific case, if SkiaSharp uses a specific static library, we'd ideally capture that fact in the packages section of the SBOM produced when building SkiaSharp.

When all of the pieces are in place (and some may not yet be), you end up with a chain of SBOMs. If an exploit is discovered in version X of library Y, then you walk backwards from your SBOM to all contributing SBOM's (including transitive dependencies) to see if any of them use that version of that library. There's definitely an opportunity for tooling improvement in that space, but at this point we're still creating the building blocks.

Since no further action is needed from our team, I'll close out this issue. If you have other SBOM-related issues, please feel free to open a new issue.

Thanks for your interest in SBOM!
