### ISSUE TITLE
Can't generate an SBOM for directories containing a space

### ISSUE THREAD

**Issue by henning-krause** [microsoft/sbom-tool#72]
I execute this command on Windows (doesn't matter if I use cmd or PowerShell):

```
C:\Temp\sbom-tool.exe generate -b "C:\src\core\Build\Service with spaces" -bc "C:\src\core\Solutions\service with spaces\src\" -pn "Foo bar services" -pv "1.0.0.0" -nsb "https://example.com"
```
The tool runs and creates a manifest, however no depedencies are found.

Program output:
```
[INFO] Log file: C:\Users\username\AppData\Local\Temp\GovCompDisc_Log_20220722135038.log
[INFO] Run correlation id: 77b85f03-caa7-47b4-bc71-94e9e4b003c1

[INFO] Attempting to load default detectors
[INFO] 19 detectors were found in Microsoft.ComponentDetection.Detectors

[WARN] Provided search path C:\Users\username\AppData\Local\Temp\.net\sbom-tool\lpvnvva1.mst\Plugins does not exist.


[INFO] Finding components...
[INFO] No instructions received to scan docker images.
[ERROR] Root directory doesn't exist: C:\src\core\Solutions\service
```

If I run the tool on a directory without spaces, everything works fine.

**Comment by grantmi** [comment]
Unless I am missing something I don't think this issue is fixed. I am running sbom tool version V2.2.6 from the Command prompt.

eg. sbom generate -b “C:\Code\Directory with space” -bc “C:\Code\Directory with space” -pn MyPackage -pv 1.0.0 -ps MyCompany -nsb https://mycompany.com

gives: Unexpected argument: with
