### ISSUE TITLE
Dev/stage/prod dependencies

### ISSUE THREAD

**Issue by sachinshaji** [microsoft/sbom-tool#78]
Is there a way to filter out dependencies? In my case I want to include only production dependencies and opt out dev/stage dependencies. Is that a possible option? I believe by default Microsoft SBOM generator will capture all dependencies and generate BOM.

**Comment by aasim** [comment]
@sachinshaji You are correct, currently we don't have a way to seperate out dev/stage dependencies from production.

**Comment by edgarrs** [comment]
@ksigmund , I think you work on a feature to filter our packages from SBOM specifying the exceptions in the command line, right?

**Comment by ksigmund** [comment]
What I'd added was a way to specify additional arguments to component detection.

**Comment by edgarrs** [comment]
@sachinshaji , would the ability to exclude folders for dependencies detection help you in this case?

**Comment by sachinshaji** [comment]
Sorry to say that it didn't. Our dev/stage/prod dependencies are present in a single file so the mentioned approach couldn't solve the issue.
Thanks for the response

**Comment by karlmoor-cisco** [comment]
The component detection documentation seems to suggest that test dependencies are at least flagged up at this stage. Couldn't this be exposed as an argument to respect this flag and to include or exclude them based on this? At the minute it appears test dependencies in maven are not treated any differently.

https://github.com/microsoft/component-detection/blob/7537eed5e6becb8eb1dd6662e5ef6d346776b097/docs/detectors/maven.md

**Comment by edgarrs** [comment]
@daneshbadlani to follow up to see if there are other component detectors other than maven that flag test or development dependencies

**Comment by karlmoor-cisco** [comment]
> @daneshbadlani to follow up to see if there are other component detectors other than maven that flag test or development dependencies

There appears to be an open ticket against this. I would suggest that it's the component detection projects issue and `sbom-tool` is aligned to that. Once that issue is resolved, it's just a case of pulling in the new version of their code.

https://github.com/microsoft/component-detection/issues/198

**Comment by edgarrs** [comment]
Once component detectors adds this functionality we will prioritize the integration with the sbom tool

**Comment by karlmoor-cisco** [comment]
> Once component detectors adds this functionality we will prioritize the integration with the sbom tool

Would it make sense to comment on the related ticket as such. Whilst it shows a linkage, nobody will necessarily know that this is the case.

**Comment by mvarblow** [comment]
I see that the component-detection library has a feature they call "development dependencies labeling". And it is implemented for several of the detectors, including npm.

https://github.com/microsoft/component-detection/blob/main/docs/feature-overview.md

Could this be used to exclude npm "devDependencies"? It seems like that would be necessary to get useful output from sbom-tool. This is all we're currently lacking to filter out dev dependencies. Or can it already be done?

**Comment by jlperkins** [comment]
Current SBOM team is unaware of a use case where we want to filter anything out of an SBOM. More information needed to reasses.

**Comment by mvarblow** [comment]
@jlperkins, the use case is that you're constructing a SBOM which is meant to contain only the software dependencies which you actually distribute with your product. You use a package manager (e.g. NuGet or npm) to obtain both dependencies which ship with the product and dependencies which are used only to build your product. If the SBOM tool includes all the dependencies from the npm and nuget manifests without filtering out the dev/build dependencies, then the SBOM will be misleading. It will not accurately reflect the dependencies which are included in the product you're distributing.

**Comment by mvarblow** [comment]
@jlperkins See my comment above. This seems like a fairly common use case. It's certainly a use case that we're very interested in. Are you willing to consider reopening this issue?

**Comment by mvarblow** [comment]
Adding to the comments above... what we're _really_ interested in is excluding the npm devDependencies. These dependencies are used for building our web assets but are **not** distributed with the application. Including them in the SBOM (along with all the dependencies of the devDependencies) significantly bloats the generated SBOM with information that is, frankly, misleading/inaccurate.

**Comment by henning-krause** [comment]
@jlperkins  We'd also like to remove our devdependencies from our SBOM. I think is a valid use case.

Would be great if you could support that.

**Comment by jlperkins** [comment]
Sorry for the delay in responding here. I will bring this up with my team and we will discuss... thank you for your patience!

**Comment by jlperkins** [comment]
Hi all @henning-krause @mvarblow, we've met and reaffirmed that we do want to keep all dependencies in the SBOM, and not offer the option to opt-out from including dev dependencies. I know this is not the answer you are hoping for, but we have a reason why. If SBOMs were only distributed externally, it would make more sense to only document what's shipped. However, SBOMs have a dual use case, where internally, they can be used for tracing vulnerabilities to affected products. For this case, we want to capture everything which could potentially impact the final product, which includes the dev dependencies. We recognize that this is documenting different kinds of dependencies in the same way, and down the line we may separate these by using VEX or another format... but at this time, we do not intend to provide a way to exclude any dependencies from an SBOM, dev or otherwise.
